"""
python/pdsl/codegen.py
PDSL code generator: PDSL AST -> Python source code.

The generated code:
  - Creates a subclass of Model ABC for each PDSL model
  - Implements forward_batch() using vectorised NumPy
  - Creates a list of Distribution priors
  - Returns a runnable (model, priors, run_config) tuple

Supported math functions in PDSL expressions:
  exp, log, sqrt, abs, sin, cos, tanh, clip
"""

from __future__ import annotations

from python.pdsl.ast_nodes import (
    BinOp, DistributionNode, Expr, FuncCall,
    ModelNode, NumberLit, Pow, Program,
    UnaryOp, Var,
)

# Math functions available in PDSL and their NumPy equivalents
_MATH_FUNCS: dict[str, str] = {
    "exp":  "np.exp",
    "log":  "np.log",
    "sqrt": "np.sqrt",
    "abs":  "np.abs",
    "sin":  "np.sin",
    "cos":  "np.cos",
    "tanh": "np.tanh",
    "clip": "np.clip",
}

# Distribution name -> Python class name
_DIST_CLASSES: dict[str, str] = {
    "Normal":    "Normal",
    "LogNormal": "LogNormal",
    "Uniform":   "Uniform",
    "Beta":      "Beta",
}


def _expr_to_python(expr: Expr) -> str:
    """Recursively convert an AST expression to a Python string."""
    if isinstance(expr, NumberLit):
        return repr(expr.value)

    if isinstance(expr, Var):
        return expr.name

    if isinstance(expr, BinOp):
        left  = _expr_to_python(expr.left)
        right = _expr_to_python(expr.right)
        return f"({left} {expr.op} {right})"

    if isinstance(expr, UnaryOp):
        operand = _expr_to_python(expr.operand)
        return f"({expr.op}{operand})"

    if isinstance(expr, Pow):
        base = _expr_to_python(expr.base)
        exp  = _expr_to_python(expr.exp)
        return f"({base} ** {exp})"

    if isinstance(expr, FuncCall):
        np_func = _MATH_FUNCS.get(expr.name)
        if np_func is None:
            raise ValueError(
                f"Unknown function '{expr.name}' in PDSL expression. "
                f"Supported: {sorted(_MATH_FUNCS.keys())}"
            )
        args = ", ".join(_expr_to_python(a) for a in expr.args)
        return f"{np_func}({args})"

    raise TypeError(f"Unknown expression type: {type(expr)}")


def _dist_to_python(name: str, dist: DistributionNode) -> str:
    """Convert a DistributionNode to a Python constructor call."""
    cls = _DIST_CLASSES.get(dist.name)
    if cls is None:
        raise ValueError(
            f"Unknown distribution '{dist.name}'. "
            f"Supported: {sorted(_DIST_CLASSES.keys())}"
        )
    args = ", ".join(repr(a) for a in dist.args)
    return f"{cls}({args})"


def generate(program: Program) -> str:
    """
    Generate Python source code from a PDSL Program AST.

    The generated module exports:
      - One Model subclass per PDSL model block
      - One build_priors() function per model
      - One run_config dict per model

    Parameters
    ----------
    program : Program
        Parsed PDSL AST.

    Returns
    -------
    str
        Complete Python source code, ready to exec() or write to a file.
    """
    lines: list[str] = []

    # Header
    lines += [
        "# AUTO-GENERATED by ProbOS PDSL compiler v0.1",
        "# DO NOT EDIT -- edit the .pdsl source instead",
        "from __future__ import annotations",
        "import numpy as np",
        "from python.src.state import Model, FloatArray",
        "from python.src.distributions import (",
        "    Normal, LogNormal, Uniform, Beta",
        ")",
        "",
    ]

    for model in program.models:
        lines += _generate_model(model)
        lines.append("")

    return "\n".join(lines)


def _generate_model(model: ModelNode) -> list[str]:
    lines: list[str] = []
    class_name = f"PDSL_{model.name.capitalize()}Model"
    n_states   = len(model.states)
    n_params   = len(model.params)

    state_names = [s.name for s in model.states]
    param_names = [p.name for p in model.params]

    # ------------------------------------------------------------------
    # Model class
    # ------------------------------------------------------------------
    lines += [
        f"# Model: {model.name}",
        f"class {class_name}(Model):",
        f'    """PDSL-generated model: {model.name}"""',
        "",
        "    @property",
        "    def state_dim(self) -> int:",
        f"        return {n_states}",
        "",
        "    @property",
        "    def param_dim(self) -> int:",
        f"        return {n_params}",
        "",
        "    def param_names(self) -> list[str]:",
        f"        return {param_names!r}",
        "",
        "    def initial_state(self) -> FloatArray:",
        "        return np.array([",
    ]
    for s in model.states:
        lines.append(f"            {s.init!r},  # {s.name}")
    lines += [
        "        ], dtype=np.float64)",
        "",
    ]

    # ------------------------------------------------------------------
    # forward_batch
    # ------------------------------------------------------------------
    lines += [
        "    def forward_batch(",
        "        self,",
        "        state:  FloatArray,",
        "        params: FloatArray,",
        "        dt:     float,",
        "    ) -> FloatArray:",
        '        """Vectorised Euler step -- generated from PDSL drift equations."""',
    ]

    # Extract state variables
    for i, name in enumerate(state_names):
        lines.append(f"        {name} = state[:, {i}]")
    lines.append("")

    # Extract param variables
    for i, name in enumerate(param_names):
        lines.append(f"        {name} = params[:, {i}]")
    lines.append("")

    # Compute drifts
    # Build a mapping from state_name -> drift expr
    drift_map: dict[str, str] = {}
    for drift in model.drifts:
        drift_map[drift.state_name] = _expr_to_python(drift.expr)

    for name in state_names:
        if name in drift_map:
            lines.append(f"        d_{name} = {drift_map[name]}")
        else:
            lines.append(f"        d_{name} = np.zeros_like({name})")
    lines.append("")

    # Euler update
    for name in state_names:
        lines.append(f"        new_{name} = {name} + dt * d_{name}")
    lines.append("")

    # v0.1 safety net: clip all states to a wide physical range to prevent
    # numerical blowup from runaway Arrhenius terms. Production PDSL (v0.2)
    # will let users declare explicit bounds per state variable.
    lines.append("        # PDSL v0.1 safety clip -- prevents numerical blowup")
    for name in state_names:
        lines.append(f"        new_{name} = np.clip(new_{name}, -1e6, 1e6)")
    lines.append("")

    # Pack result
    lines.append("        return np.column_stack([")
    for name in state_names:
        lines.append(f"            new_{name},")
    lines.append("        ])")
    lines.append("")

    # ------------------------------------------------------------------
    # build_priors function
    # ------------------------------------------------------------------
    lines += [
        f"def build_{model.name}_priors() -> list:",
        f'    """Prior distributions for {model.name} model parameters."""',
        "    return [",
    ]
    for p in model.params:
        dist_str = _dist_to_python(p.name, p.distribution)
        lines.append(f"        {dist_str},  # {p.name}")
    lines += [
        "    ]",
        "",
    ]

    # ------------------------------------------------------------------
    # run_config dict
    # ------------------------------------------------------------------
    cfg = model.run
    lines += [
        f"{model.name}_run_config = {{",
        f"    'N':     {cfg.N},",
        f"    'steps': {cfg.steps},",
        f"    'dt':    {cfg.dt},",
        f"    'seed':  {cfg.seed},",
        "}",
        "",
    ]

    return lines
